### ISSUE TITLE
localStorage and fallback to http

### ISSUE THREAD

**Issue by eeejayg** [js-data/js-data-localstorage#12]
I am using js-data and js-data-localstorage in Angular.  The run function of my main controller looks like:

    .run(function( DS ) {
        DS.registerAdapter('localstorage', new DSLocalStorageAdapter(), { default: false });
    })

(1) What does "default:true" or "default:false" mean in this instance?

(2) How do I make it fall back to an http request if the item is not found in local storage?  (And of course, once it makes an http request it should be put in local storage.)

Thank you so much.

**Comment by jmdobry** [comment]
1) `default: true` makes the adapter the default adapter to be used for async operations, otherwise you would have to specify which adapter to use.

2) You're looking for the `fallbackStrategy` and `fallbackAdapters` options: http://www.js-data.io/docs/dsdefaults#fallbackadapters http://www.js-data.io/docs/dsfind http://www.js-data.io/docs/dsfindall

To sync to localStorage, check out this example: https://gist.github.com/jmdobry/cf489a3025b8087fe21a

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).
