### ISSUE TITLE
Accessing LocalDataStore in Angular

### ISSUE THREAD

**Issue by eeejayg** [js-data/js-data-localstorage#13]
Thank you so much for addressing my previous question.  So in this scenario:

.run(function( DS ) {
    DS.registerAdapter('localstorage', new DSLocalStorageAdapter(), { default: false });
})

i am going to want add items retrieved from http using afterCreate.  In your Gist you have:

var ls = new DSLocalStorageAdapter();

and you use ls.create to store items in local storage.  In my scenario above, how do I access the local storage object?  Is the local storage object hanging off of DS somewhere?

**Comment by jmdobry** [comment]
Please use the [Gitter Channel](https://gitter.im/js-data/js-data) or [mailing list](https://groups.io/org/groupsio/jsdata) for support questions.


This plunker shows how to access data (via DS) that was saved (via DS) to localStorage: http://plnkr.co/edit/yVQden?p=preview

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).
